name: Release
on:
   push:
      branches: [main]
jobs:
   build:
      name: Deployment
      runs-on: ubuntu-latest
      permissions:
         packages: write
      steps:
         - name: Checkout
           uses: actions/checkout@v2
           with:
              fetch-depth: 0

           # Configure git to commit and push to main
         - name: Setup GIT
           run: |
              git switch -c version-branch
              git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
              git config user.name "$GITHUB_ACTOR"

         - name: "Automated Version Bump"
           run: npm version patch

         - name: Update & Push
           env:
              GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
           run: |
              git add .
              git commit --allow-empty -m "bump version"
              git push origin version-branch:main

         # Create Release
         - name: Release
           uses: justincy/github-action-npm-release@2.0.2
           id: release
         - name: Print release output
           if: ${{ steps.release.outputs.released == 'true' }}
           run: echo Release ID ${{ steps.release.outputs.release_id }}
